"""add approved_at to group_members


Revision ID: 6952c83fd237
Revises: f3c1e4866dac
Create Date: 2024-12-10 16:12:36.213906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6952c83fd237'
down_revision: Union[str, None] = 'f3c1e4866dac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_members', sa.Column('approved_at', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'approved_at')
    # ### end Alembic commands ###
