"""indexing word table

Revision ID: 6d3298d40a7b
Revises: 7ccfd57b827f
Create Date: 2024-12-02 11:26:18.849729

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "6d3298d40a7b"
down_revision: Union[str, None] = "7ccfd57b827f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_words_word"), "words", ["word"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_words_word"), table_name="words")
    # ### end Alembic commands ###
