"""Add words table

Revision ID: 84208112414c
Revises: fc584283aa78
Create Date: 2024-10-06 11:55:49.377423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84208112414c'
down_revision: Union[str, None] = 'fc584283aa78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=True),
    sa.Column('ipa', sa.String(length=64), nullable=True),
    sa.Column('mean', sa.String(length=2048), nullable=True),
    sa.Column('difficult_level', sa.Integer(), nullable=True),
    sa.Column('path_of_speech', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    comment='word dictionary'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
