"""Add group table

Revision ID: 9a37a14f9415
Revises: f71ecf438fbc
Create Date: 2024-10-30 13:40:38.303913

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9a37a14f9415"
down_revision: Union[str, None] = "f71ecf438fbc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups",
        sa.Column(
            "created_at",
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("updated_by", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=64), nullable=True),
        sa.Column("description", sa.String(length=2048), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        comment="groups",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("groups")
    # ### end Alembic commands ###
